name: gh-tracker
description: A Github follow tracker to easily check who recently follows/unfollowed
author: lazuee

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'activity'
  color: 'green'
