name: Update Tracker
on:
    workflow_dispatch:
    schedule:
        - cron: "*/5 * * * *"

jobs:
    tracker:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: lazuee/github-tracker@1.0.3
              env:
                GH_TOKEN: ${{ secrets.GH_TOKEN }}