name: Update Tracker
on:
    workflow_dispatch:
    schedule:
        - cron: "*/5 * * * *"

jobs:
    tracker:
        runs-on: ubuntu-latest
        steps:
            - uses: ./
              env:
                GH_TOKEN: ${{ secrets.GH_TOKEN }}